# .github/workflows/run-script.yml
name: update alert conditions

on:
  workflow_dispatch:
    inputs:
        alert_payload:
          description: 'JSON input for alert updates'
          required: true
          type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::167376044282:role/Test-OIDC_role
          aws-region: us-west-2

      - name: Parse JSON input
        id: parse
        run: |
          echo '${{ github.event.inputs.alert_payload }}' > input.json
          cat input.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install boto3 requests

      - name: Run Python Script
        run: python update_runbook_url.py
